### ISSUE TITLE
Create a Dropdown To display tables

### ISSUE THREAD

**Issue by rakaar** [tsg-iitkgp/tsg#15]
A table for 
- Events
- GC
- Open IIT

**Comment by LIGHT1210** [comment]
1) societies and fests combined to socult(also in mobile)
2) notices make it a dropdown including announcements, open iit, GC 19-20, GC 18-19
3) between notices and inter iit include information( include mess menu, GC rulebook, open iit rule book)

**Comment by thealphadollar** [comment]
The PR for the same is #36 

It has to be reviewed by @rakaar for design improvements. Post that it can be merged.
