### ISSUE TITLE
Create a page for mess menu

### ISSUE THREAD

**Issue by thealphadollar** [tsg-iitkgp/tsg#22]
This page would need to display a dropdown and accordingly a hall would be selected; the sheet for the same has already been made. It is also important to then display the data nicely in a tabular form.

https://github.com/tsg-iitkgp/Gymkhana-BackServer/issues/2

**Comment by PrashikD** [comment]
Made a page with the hall dropdown list and menu table display

**Comment by thealphadollar** [comment]
https://github.com/tsg-iitkgp/tsg/pull/31 adds page without the JS logic for displaying the mess menu.

Currently backend doesn't have the required endpoint and hence only post that we will work again on this.
