### ISSUE TITLE
Add SEO Meta-tags

### ISSUE THREAD

**Issue by thealphadollar** [tsg-iitkgp/tsg#43]
https://www.searchenginewatch.com/2018/04/04/a-quick-and-easy-guide-to-meta-tags-in-seo/

Using the above link as reference, add SEO meta tags to all the pages of the website.

@rakaar Please help @LIGHT1210 and @139Vaibhav work on the issue but DO NOT complete it by yourself. Everyone should be learning and doing stuff.

**Comment by rakaar** [comment]
@LIGHT1210 and @139Vaibhav . Lets add tags as per [this](https://css-tricks.com/essential-meta-tags-social-media/)  and then go to rest of tags (canonical , robots) as per the link in the issue

**Comment by thealphadollar** [comment]
@LIGHT1210 @139Vaibhav

**Comment by thealphadollar** [comment]
@rakaar Please see if anymore update is required in this regard.

**Comment by rakaar** [comment]
@thealphadollar  I don't know what has happened regarding this. @139Vaibhav  @LIGHT1210  any updates?

**Comment by thealphadollar** [comment]
There are meta headers added, please see if anything else is required.

**Comment by rakaar** [comment]
I couldn't find the robots meta tag, rest all seems  fine to me.
